### ISSUE TITLE
Testing the Issue System

### ISSUE THREAD

**Issue by JavaIsNotMagic** [JavaIsNotMagic/MinecraftLauncher-Python#2]
Hey all, 

This is just a test. You can ignore this issue, but please do not close it.

**Comment by scoutchorton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Test](https://trello.com/c/5aMsj7S5/1-test)

**Comment by JavaIsNotMagic** [comment]
System works. Issue closed
